#!/usr/bin/env python3

import json
import os
import re

JIRA_URL = 'https://ultidev'
JIRA_PROJECT = 'PRO'

issue_pattern = f'({JIRA_PROJECT}-\\d+)'
url_pattern = f'{JIRA_URL}/browse/{issue_pattern}'
link_pattern = f'\\[[^\\]]+\\]\\({url_pattern}\\)'

patterns = [
  f'({keyword})(?: |:| :|: | : ){pattern}'
  for keyword in ['closes', 'ref', 'refs', 'references']
  for pattern in [issue_pattern, url_pattern, link_pattern]
]

regexps = list(map(lambda p: re.compile(p, re.I), patterns))


def find_issues(text, patterns=regexps):
  return [
    match
    for regexp in patterns
    for match in re.findall(regexp, text)
  ]


if __name__ == '__main__':
  data = json.loads(os.environ['GITHUB_EVENT_DATA'])
  if 'pull_request' in data:
    issues = {issue for (keyword, issue) in find_issues(data['pull_request']['body'])}
    issues |= re.findall(issue_pattern, data['pull_request']['body'])
    if len(issues):
      print('Found issues: ', ', '.join(issues))
    else:
      print('Found no issues')
  else:
    print('No data found')
