name: Jira PR hook
on:
  pull_request:
    types:
      - closed
jobs:
  jira_hook:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Call Jira hook
        env:
          GITHUB_EVENT_DATA: ${{ toJson(github.event) }}
        run: |
          ./scripts/jira-hook
